name: shared_preferences_stub
description: Flutter plugin for reading and writing simple key-value pairs.
  Wraps NSUserDefaults on iOS and SharedPreferences on Android.
author: Aloïs Deniel <alois.deniel@outlook.com>
homepage: https://github.com/alois_deniel/flutter_plugins_stubs
version: 0.5.3+2

dependencies:
  meta: 1.1.6

environment:
  sdk: ">=2.1.0 <3.0.0"