name: shared
description: A new shared project.
version: 1.0.0+1
 
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  url_launcher_stub:
    path: ../../packages/url_launcher_stub
  shared_preferences_stub: 
    path: ../../packages/shared_preferences_stub
  connectivity_stub: 
    path: ../../packages/connectivity_stub
  change_notifier_stub:
    path: ../../packages/change_notifier_stub